# Generated by Django 4.2.7 on 2025-06-10 14:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marchandise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la marchandise')),
                ('poids', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)])),
                ('volume', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)])),
                ('type_cargaison', models.CharField(choices=[('R', 'Routière'), ('A', 'Aérienne')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cargaison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_cargaison', models.CharField(choices=[('R', 'Routière'), ('A', 'Aérienne')], max_length=1)),
                ('distance', models.FloatField(validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marchandises', models.ManyToManyField(to='transport.marchandise')),
            ],
        ),
    ]
